// Copyright (c) 2018 Anki, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the file LICENSE.txt or at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Behavior related messages

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.4
// source: behavior.proto

package vectorpb

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Where in the behavior tree the SDK code should be executed.
type ControlRequest_Priority int32

const (
	// Unknown priority. Used for versions that don't understand old priority levels.
	ControlRequest_UNKNOWN ControlRequest_Priority = 0
	// Highest priority level. Suppresses most automatic physical reactions, use with caution.
	ControlRequest_OVERRIDE_BEHAVIORS ControlRequest_Priority = 10
	// Normal priority level. Directly under mandatory physical reactions.
	ControlRequest_DEFAULT ControlRequest_Priority = 20
	// Enable long-running SDK control between script execution.  Not to be used for regular behavior control.
	ControlRequest_RESERVE_CONTROL ControlRequest_Priority = 30
)

// Enum value maps for ControlRequest_Priority.
var (
	ControlRequest_Priority_name = map[int32]string{
		0:  "UNKNOWN",
		10: "OVERRIDE_BEHAVIORS",
		20: "DEFAULT",
		30: "RESERVE_CONTROL",
	}
	ControlRequest_Priority_value = map[string]int32{
		"UNKNOWN":            0,
		"OVERRIDE_BEHAVIORS": 10,
		"DEFAULT":            20,
		"RESERVE_CONTROL":    30,
	}
)

func (x ControlRequest_Priority) Enum() *ControlRequest_Priority {
	p := new(ControlRequest_Priority)
	*p = x
	return p
}

func (x ControlRequest_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_behavior_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_Priority) Type() protoreflect.EnumType {
	return &file_behavior_proto_enumTypes[0]
}

func (x ControlRequest_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_Priority.Descriptor instead.
func (ControlRequest_Priority) EnumDescriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{1, 0}
}

// Tell the behavior stream to release control from the SDK.
// The stream may stay alive, but Vector will be allowed to run
// his normal behaviors.
type ControlRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ControlRelease) Reset() {
	*x = ControlRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRelease) ProtoMessage() {}

func (x *ControlRelease) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRelease.ProtoReflect.Descriptor instead.
func (*ControlRelease) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{0}
}

// Request control of the behavior system at a given priority.
// Currently there is only one priority level.
type ControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Where in the behavior tree the SDK code should be executed.
	Priority ControlRequest_Priority `protobuf:"varint,1,opt,name=priority,proto3,enum=Anki.Vector.external_interface.ControlRequest_Priority" json:"priority,omitempty"`
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{1}
}

func (x *ControlRequest) GetPriority() ControlRequest_Priority {
	if x != nil {
		return x.Priority
	}
	return ControlRequest_UNKNOWN
}

// Messages that can be sent to the behavior stream. Explicitly
// requesting or releasing control.
type BehaviorControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestType:
	//	*BehaviorControlRequest_ControlRelease
	//	*BehaviorControlRequest_ControlRequest
	RequestType isBehaviorControlRequest_RequestType `protobuf_oneof:"request_type"`
}

func (x *BehaviorControlRequest) Reset() {
	*x = BehaviorControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BehaviorControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorControlRequest) ProtoMessage() {}

func (x *BehaviorControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorControlRequest.ProtoReflect.Descriptor instead.
func (*BehaviorControlRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{2}
}

func (m *BehaviorControlRequest) GetRequestType() isBehaviorControlRequest_RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

func (x *BehaviorControlRequest) GetControlRelease() *ControlRelease {
	if x, ok := x.GetRequestType().(*BehaviorControlRequest_ControlRelease); ok {
		return x.ControlRelease
	}
	return nil
}

func (x *BehaviorControlRequest) GetControlRequest() *ControlRequest {
	if x, ok := x.GetRequestType().(*BehaviorControlRequest_ControlRequest); ok {
		return x.ControlRequest
	}
	return nil
}

type isBehaviorControlRequest_RequestType interface {
	isBehaviorControlRequest_RequestType()
}

type BehaviorControlRequest_ControlRelease struct {
	// Release control of the behavior system back to Vector.
	ControlRelease *ControlRelease `protobuf:"bytes,1,opt,name=control_release,json=controlRelease,proto3,oneof"`
}

type BehaviorControlRequest_ControlRequest struct {
	// Request control of the behavior system for the SDK.
	ControlRequest *ControlRequest `protobuf:"bytes,2,opt,name=control_request,json=controlRequest,proto3,oneof"`
}

func (*BehaviorControlRequest_ControlRelease) isBehaviorControlRequest_RequestType() {}

func (*BehaviorControlRequest_ControlRequest) isBehaviorControlRequest_RequestType() {}

// The SDK user is now free to run any actions and behaviors they like.
// Until a ControlLostResponse is received, they are directly in control
// of Vector's behavior system.
type ControlGrantedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ControlGrantedResponse) Reset() {
	*x = ControlGrantedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlGrantedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlGrantedResponse) ProtoMessage() {}

func (x *ControlGrantedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlGrantedResponse.ProtoReflect.Descriptor instead.
func (*ControlGrantedResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{3}
}

// This informs the user that they lost control of the behavior system.
// All direct actions will be unavailable via the sdk until control is regained.
// Regaining control can be either through a call to ControlRequest, or
// can be as a result of conditions passed to the original ControlRequest.
type ControlLostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ControlLostResponse) Reset() {
	*x = ControlLostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlLostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlLostResponse) ProtoMessage() {}

func (x *ControlLostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlLostResponse.ProtoReflect.Descriptor instead.
func (*ControlLostResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{4}
}

// The ability to reserve control before/after SDK scripts has been lost.
// This control can be regained through another ControlRequest.
type ReservedControlLostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReservedControlLostResponse) Reset() {
	*x = ReservedControlLostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservedControlLostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservedControlLostResponse) ProtoMessage() {}

func (x *ReservedControlLostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservedControlLostResponse.ProtoReflect.Descriptor instead.
func (*ReservedControlLostResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{5}
}

// Responses from the behavior stream.
type BehaviorControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ResponseType:
	//	*BehaviorControlResponse_ControlGrantedResponse
	//	*BehaviorControlResponse_ControlLostEvent
	//	*BehaviorControlResponse_KeepAlive
	//	*BehaviorControlResponse_ReservedControlLostEvent
	ResponseType isBehaviorControlResponse_ResponseType `protobuf_oneof:"response_type"`
}

func (x *BehaviorControlResponse) Reset() {
	*x = BehaviorControlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BehaviorControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorControlResponse) ProtoMessage() {}

func (x *BehaviorControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorControlResponse.ProtoReflect.Descriptor instead.
func (*BehaviorControlResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{6}
}

func (m *BehaviorControlResponse) GetResponseType() isBehaviorControlResponse_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func (x *BehaviorControlResponse) GetControlGrantedResponse() *ControlGrantedResponse {
	if x, ok := x.GetResponseType().(*BehaviorControlResponse_ControlGrantedResponse); ok {
		return x.ControlGrantedResponse
	}
	return nil
}

func (x *BehaviorControlResponse) GetControlLostEvent() *ControlLostResponse {
	if x, ok := x.GetResponseType().(*BehaviorControlResponse_ControlLostEvent); ok {
		return x.ControlLostEvent
	}
	return nil
}

func (x *BehaviorControlResponse) GetKeepAlive() *KeepAlivePing {
	if x, ok := x.GetResponseType().(*BehaviorControlResponse_KeepAlive); ok {
		return x.KeepAlive
	}
	return nil
}

func (x *BehaviorControlResponse) GetReservedControlLostEvent() *ReservedControlLostResponse {
	if x, ok := x.GetResponseType().(*BehaviorControlResponse_ReservedControlLostEvent); ok {
		return x.ReservedControlLostEvent
	}
	return nil
}

type isBehaviorControlResponse_ResponseType interface {
	isBehaviorControlResponse_ResponseType()
}

type BehaviorControlResponse_ControlGrantedResponse struct {
	// The SDK user is now free to directly control Vector.
	ControlGrantedResponse *ControlGrantedResponse `protobuf:"bytes,1,opt,name=control_granted_response,json=controlGrantedResponse,proto3,oneof"`
}

type BehaviorControlResponse_ControlLostEvent struct {
	// Control of the behavior system has been lost to a higher priority behavior.
	ControlLostEvent *ControlLostResponse `protobuf:"bytes,2,opt,name=control_lost_event,json=controlLostEvent,proto3,oneof"`
}

type BehaviorControlResponse_KeepAlive struct {
	// Used by Vector to verify the connection is still alive.
	KeepAlive *KeepAlivePing `protobuf:"bytes,3,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type BehaviorControlResponse_ReservedControlLostEvent struct {
	// Behavior system lock has been lost to another connection
	ReservedControlLostEvent *ReservedControlLostResponse `protobuf:"bytes,4,opt,name=reserved_control_lost_event,json=reservedControlLostEvent,proto3,oneof"`
}

func (*BehaviorControlResponse_ControlGrantedResponse) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_ControlLostEvent) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_KeepAlive) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_ReservedControlLostEvent) isBehaviorControlResponse_ResponseType() {}

var File_behavior_proto protoreflect.FileDescriptor

var file_behavior_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1e, 0x41, 0x6e, 0x6b, 0x69, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x1a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x41, 0x6e, 0x6b, 0x69, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x51, 0x0a, 0x08, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x56, 0x45, 0x52, 0x52, 0x49, 0x44, 0x45, 0x5f,
	0x42, 0x45, 0x48, 0x41, 0x56, 0x49, 0x4f, 0x52, 0x53, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x14, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x1e, 0x22, 0xde, 0x01,
	0x0a, 0x16, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x59, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x41, 0x6e, 0x6b, 0x69, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x41,
	0x6e, 0x6b, 0x69, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x0e,
	0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x18,
	0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd1,
	0x03, 0x0a, 0x17, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x18, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x41,
	0x6e, 0x6b, 0x69, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63,
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6c, 0x6f, 0x73, 0x74, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x41, 0x6e, 0x6b,
	0x69, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x0a, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x41, 0x6e, 0x6b, 0x69, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x7c, 0x0a, 0x1b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6c, 0x6f, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x41, 0x6e, 0x6b, 0x69, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x18, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x2d, 0x64, 0x72, 0x65, 0x61, 0x6d, 0x2d, 0x6c,
	0x61, 0x62, 0x73, 0x2f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64,
	0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_behavior_proto_rawDescOnce sync.Once
	file_behavior_proto_rawDescData = file_behavior_proto_rawDesc
)

func file_behavior_proto_rawDescGZIP() []byte {
	file_behavior_proto_rawDescOnce.Do(func() {
		file_behavior_proto_rawDescData = protoimpl.X.CompressGZIP(file_behavior_proto_rawDescData)
	})
	return file_behavior_proto_rawDescData
}

var file_behavior_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_behavior_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_behavior_proto_goTypes = []interface{}{
	(ControlRequest_Priority)(0),        // 0: Anki.Vector.external_interface.ControlRequest.Priority
	(*ControlRelease)(nil),              // 1: Anki.Vector.external_interface.ControlRelease
	(*ControlRequest)(nil),              // 2: Anki.Vector.external_interface.ControlRequest
	(*BehaviorControlRequest)(nil),      // 3: Anki.Vector.external_interface.BehaviorControlRequest
	(*ControlGrantedResponse)(nil),      // 4: Anki.Vector.external_interface.ControlGrantedResponse
	(*ControlLostResponse)(nil),         // 5: Anki.Vector.external_interface.ControlLostResponse
	(*ReservedControlLostResponse)(nil), // 6: Anki.Vector.external_interface.ReservedControlLostResponse
	(*BehaviorControlResponse)(nil),     // 7: Anki.Vector.external_interface.BehaviorControlResponse
	(*KeepAlivePing)(nil),               // 8: Anki.Vector.external_interface.KeepAlivePing
}
var file_behavior_proto_depIdxs = []int32{
	0, // 0: Anki.Vector.external_interface.ControlRequest.priority:type_name -> Anki.Vector.external_interface.ControlRequest.Priority
	1, // 1: Anki.Vector.external_interface.BehaviorControlRequest.control_release:type_name -> Anki.Vector.external_interface.ControlRelease
	2, // 2: Anki.Vector.external_interface.BehaviorControlRequest.control_request:type_name -> Anki.Vector.external_interface.ControlRequest
	4, // 3: Anki.Vector.external_interface.BehaviorControlResponse.control_granted_response:type_name -> Anki.Vector.external_interface.ControlGrantedResponse
	5, // 4: Anki.Vector.external_interface.BehaviorControlResponse.control_lost_event:type_name -> Anki.Vector.external_interface.ControlLostResponse
	8, // 5: Anki.Vector.external_interface.BehaviorControlResponse.keep_alive:type_name -> Anki.Vector.external_interface.KeepAlivePing
	6, // 6: Anki.Vector.external_interface.BehaviorControlResponse.reserved_control_lost_event:type_name -> Anki.Vector.external_interface.ReservedControlLostResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_behavior_proto_init() }
func file_behavior_proto_init() {
	if File_behavior_proto != nil {
		return
	}
	file_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_behavior_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BehaviorControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlGrantedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlLostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservedControlLostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BehaviorControlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_behavior_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BehaviorControlRequest_ControlRelease)(nil),
		(*BehaviorControlRequest_ControlRequest)(nil),
	}
	file_behavior_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*BehaviorControlResponse_ControlGrantedResponse)(nil),
		(*BehaviorControlResponse_ControlLostEvent)(nil),
		(*BehaviorControlResponse_KeepAlive)(nil),
		(*BehaviorControlResponse_ReservedControlLostEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_behavior_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_behavior_proto_goTypes,
		DependencyIndexes: file_behavior_proto_depIdxs,
		EnumInfos:         file_behavior_proto_enumTypes,
		MessageInfos:      file_behavior_proto_msgTypes,
	}.Build()
	File_behavior_proto = out.File
	file_behavior_proto_rawDesc = nil
	file_behavior_proto_goTypes = nil
	file_behavior_proto_depIdxs = nil
}
